swagger: "2.0"
info:
  version: "1.0.0"
  title: "Sample API"
  description: "This is a sample API documentation using Swagger."
  termsOfService: "http://example.com/terms/"
  contact:
    name: "API Support"
    url: "http://www.example.com/support"
    email: "support@example.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.example.com"
basePath: "/v1"
schemes:
  - "https"
paths: